[package]
name = "file_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
json-parser               = { path = "../../library/json/json-main" }
json-builder              = { path = "../../library/json/json-macro" }

logger-main               = { path = "../../library/log/logger-main"}